/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/reset-password` | `/reset-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cameras/add` | `/cameras/add`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cameras` | `/cameras`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cameras/map` | `/cameras/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/efa-tratra` | `/efa-tratra`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/incidents/add` | `/incidents/add`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/incidents` | `/incidents`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/reset-password` | `/reset-password`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cameras/add` | `/cameras/add`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cameras` | `/cameras`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cameras/map` | `/cameras/map`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/efa-tratra` | `/efa-tratra`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/incidents/add` | `/incidents/add`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/incidents` | `/incidents`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/reset-password${`?${string}` | `#${string}` | ''}` | `/reset-password${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cameras/add${`?${string}` | `#${string}` | ''}` | `/cameras/add${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cameras${`?${string}` | `#${string}` | ''}` | `/cameras${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cameras/map${`?${string}` | `#${string}` | ''}` | `/cameras/map${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/efa-tratra${`?${string}` | `#${string}` | ''}` | `/efa-tratra${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/incidents/add${`?${string}` | `#${string}` | ''}` | `/incidents/add${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/incidents${`?${string}` | `#${string}` | ''}` | `/incidents${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/reset-password` | `/reset-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cameras/add` | `/cameras/add`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cameras` | `/cameras`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cameras/map` | `/cameras/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/efa-tratra` | `/efa-tratra`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/incidents/add` | `/incidents/add`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/incidents` | `/incidents`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
